#Website Settings
title: Thompson Tutorials
email: info@thompsontutorial.co.uk
linkedin: https://uk.linkedin.com/pub/lewis-thompson/79/920/b65
description: "Tutoring from Lewis Thompson"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thompsontutorials.co.uk" # the base hostname & protocol for your site

# Build settings

markdown: kramdown
permalink: pretty

port: 4000 

sass:
  sass_dir: assets/css
  style: :nested  git 